global:
# collect metrics from app every 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']